url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana APT repository
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
- name: Update Grafana repository link
  ansible.builtin.template:
    src: /var/lib/jenkins/workspace/Grafana/grafana_repo.j2
    dest: /etc/apt/sources.list.d/packages_grafana_com_oss_deb.list
  become: yes


- name: Update package cache
  apt:
    update_cache: yes
- name: Install Grafana
  apt:
    name: grafana
    state: present
    update_cache: yes
- name: Start and enable Grafana service
  systemd:
    name: grafana-server
    enabled: yes
    state: started
